#!/usr/bin/with-contenv bash

# copy config
[[ ! -e /config/beets.sh ]] && \
	cp /defaults/beets.sh /config/beets.sh
[[ ! -e /config/config.yaml ]] && \
	mkdir /config/beets && \
	cp /defaults/beets/config.yaml /config/beets/config.yaml

# permissions
chown -R abc:abc \
	/config
